### ISSUE TITLE
Yii-facebook-opengraph like button error

### ISSUE THREAD

**Issue by vodanh123** [splashlab/yii-facebook-opengraph#11]
I did exactly follow the instructions here :http://www.yiiframework.com/extension/facebook-opengraph
But when I click like button, then the error appears. The error code is: 1404009. While sharing still works fine.
Here is the code:
In main.php : 
'components'=>array(
  'facebook'=>array(
    'class' => 'ext.yii-facebook-opengraph.SFacebook',
    'appId'=>'...', 
    'secret'=>'...',  ),),
In SiteController.php
protected function afterRender($view, &$output) {
  parent::afterRender($view,$output);
  Yii::app()->facebook->initJs($output); 
  Yii::app()->facebook->renderOGMetaTags();
  return true; }
In View:
<?php $this->widget('ext.yii-facebook-opengraph.plugins.LikeButton', array(
   'href' => 'https://www.facebook.com/newordersystem', 
   'show_faces'=>true,
   'send' => TRUE )); ?>  
Please help me. Thank you very much.
Sorry for my bad english.

Update: I discovered that when I logout Facebook before like the errors will not appear.So, I think one should insert code log out of facebook before like. Can someone help me?

**Comment by thaddeusmt** [comment]
Sorry I let this languish so long. Sad to say I have just updated the extension to use the new PHP SDK 4.0 and am no longer supporting the old version. Try the new extension and open a new issue if it doesn't work. Thanks
